### PR TITLE
Use Facebook API 2.2

### PR DESCRIPTION
**Pull request by antseppa**
See also: https://github.com/nemomobile/buteo-sync-plugins-social/pull/19

### CODE REVIEW

**Comment by SfietKonstantin** [comment]
LGTM

**Comment by faenil** [comment]
what about if we avoid hardcoding versions inside code? :)

**Comment by SfietKonstantin** [comment]
@faenil ATM we can leave it as is. Facebook graph API 2.X series should be a long-term release, so 2.2 won't be discontinued in 6 month.

**Comment by faenil** [comment]
ok :/

**Comment by antseppa** [comment]
@faenil you're right:  in Sailfish the Facebook API version will be an account setting and it would be good if it wasn't hard coded in n-q-p-s either. However, I'd like to get things working on top of 2.x first and add that as a later improvement. Like SfietKonstantin said, 2.2 is a long term release with guaranteed support at least until November 2016.

**Comment by chriadam** [comment]
LGTM

**Comment by antseppa** [comment]
Added missing tag to commit string.

**Pull request merged**
